# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://yoursite.com
title: CloudTUI-FTS
email: your-email@domain.com
author: subwave07
description: > # "Write an awesome description for your new site here. 
  You can edit this line in _config.yml. It will appear in your document 
  head meta (for Google search results) and in your feed.xml site 
  description.
copyright: 'Copyright &copy; 2015 subwave07. All Rights Reserved.'
credits: Landing Page 'Theme by <a href="http://startbootstrap.com/">Start Bootstrap</a>.'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: github
    url: https://github.com/IronSummitMedia/startbootstrap
